### ISSUE TITLE
`summarise_at()` with a single column results in empty `var` column

### ISSUE THREAD

**Issue by huftis** [echasnovski/ruler#6]
When one uses `summarise_at()` (in a `col_packs`) with a *single* column and the test fails, the `var` column in the results has an empty string instead of the column name.

Here’s an reprex:

```r
library(ruler)
library(dplyr)

# Check variable type of single column
my_rules = col_packs(
  col_checks = . %>%
    summarise_at(vars(Sepal.Width),
                 rules(col_type_ok = is.character))
)

# In the results, the 'var' column is set to an empty string
iris %>% 
  expose(my_rules) %>% 
  get_report()
#> Tidy data validation report:
#> # A tibble: 1 x 5
#>   pack       rule        var      id value
#>   <chr>      <chr>       <chr> <int> <lgl>
#> 1 col_checks col_type_ok ""        0 F
```

However, if the `summarise_at()` function references multiple columns, everything works fine:

```r
# Check variable type of two columns
my_rules2 = col_packs(
  col_checks = . %>%
    summarise_at(vars(Sepal.Width, Petal.Length),
                 rules(col_type_ok = is.character))
)

# In the results, the 'var' column is set to the name of the variables
iris %>% 
  expose(my_rules2) %>% 
  get_report() 
#> Tidy data validation report:
#> # A tibble: 2 x 5
#>   pack       rule        var             id value
#>   <chr>      <chr>       <chr>        <int> <lgl>
#> 1 col_checks col_type_ok Sepal.Width      0 F    
#> 2 col_checks col_type_ok Petal.Length     0 F
```

**Comment by echasnovski** [comment]
Thanks.

The current design of column packs is that their output should have names in format __'check column name'__ + __'separator'__ + __'rule name'__. Using `rules()` in `dplyr` scoped verbs handles the creation of separator and rule names. However `vars()` has one edge case which you mentioned here: if used for one column with one rule it doesn't force using names. Supplying as named argument (oddly, with arbitrary name) fixes the issue.

``` r
library(ruler)
library(dplyr)

# vars() doesn't force using column name in this edge case
iris %>%
  summarise_at(vars(Sepal.Width),
               rules(col_type_ok = is.character))
#>   ._.col_type_ok
#> 1          FALSE

# Named arguments (even with odd names) fixes this
my_rules = col_packs(
  col_checks = . %>%
    summarise_at(vars(name = Sepal.Width),
                 rules(col_type_ok = is.character))
)

# Output is as expected
iris %>% 
  expose(my_rules) %>% 
  get_report()
#> Tidy data validation report:
#> # A tibble: 1 x 5
#>   pack       rule        var            id value
#>   <chr>      <chr>       <chr>       <int> <lgl>
#> 1 col_checks col_type_ok Sepal.Width     0 F
```

Unfortunately, this is `dplyr`'s designed behavior and won't change in near future. I mentioned this in vignette "Rule Packs" (in section "Column rule packs") but, perhaps, failed at drawing attention to this :) Maybe I should mention this in help page of column and cell packs? For now I don't know how to handle this edge case more properly.

**Comment by echasnovski** [comment]
In current version (0.1.2) this behaviour is mentioned in help page of column and cell packs. Thanks for highlighting the need for this.
