### ISSUE TITLE
In PKG usage example, I get  Error: Expected a list of quosures

### ISSUE THREAD

**Issue by sfd99** [echasnovski/ruler#8]
sfd99 commented 19 minutes ago

**Hi Evgeni 

** - the ruler PKG is very useful!.
But in the example:

    mtcars %>% summarise_all(rules(enough_sum = sum(.) > 100))
    I get this :
        Error: Expected a list of quosures

What am I missing?
thanks!

**sfd99
San Francisco
latest Rstudio/R/Ubuntu Linux 14.04LTS 32bits**

**Comment by echasnovski** [comment]
I can't reproduce this. Could you, please, run the following code in clean R session (preferably using [reprex](https://cran.r-project.org/web/packages/reprex/index.html) package) and post here the output?
```
library(ruler)
library(dplyr)

mtcars %>% summarise_all(rules(enough_sum = sum(.) > 100))

sessionInfo()
```
